### ISSUE TITLE
Wrong shapeless recipes

### ISSUE THREAD

**Issue by Gantzyo** [zDevelopers/BelovedBlocks#13]
I have noticed there are some undesired shapeless recipes:
1. Log -> 1 Plank
2. Bone -> 1 Bonemeal

The first one is probably produced by getMatterRatio() due to it always returns 1.
The second one... I don't know :P

Sorry if I misspelled something!

**Comment by AmauryCarrade** [comment]
You are using the development version, are you?

Thanks for reporting, I'll look at this. The development version is completely buggy currently, as I'm currently rewriting the whole plugin.

**Comment by LuxusDarkangel** [comment]
No, this occurs on version 1.1

**Comment by AmauryCarrade** [comment]
Weird, I'm using this plugin on a server without the mentioned bugs, and the `getMatterRatio` method doesn't exist in the 1.1 version.

Except if you are using the latest Jenkins version (or manually compiled) from the last commit: this version is labelled « 1.1 » but is the 1.2 development version.

**Comment by Gantzyo** [comment]
We are using the version downloaded from bukkit webpage: http://dev.bukkit.org/bukkit-plugins/beloved-blocks/

I mentioned getMatterRatio because I checked the code from github.

**Comment by AmauryCarrade** [comment]
Weird. Can you give me the other plugins you are running, and your server's version?

**Comment by LuxusDarkangel** [comment]
We're running the latest Spigot version, and the plugin version uploaded to bukkit (1.1), without any other plugins.

**Comment by AmauryCarrade** [comment]
We were unable to reproduce this with the latest version, so we'll assume this has been fixed. Feel free to reopen if you catch this bug again in the 1.2+ version.
