### ISSUE TITLE
Stone Buttons craft doesn't work

### ISSUE THREAD

**Issue by MGSchultz-13** [zDevelopers/BelovedBlocks#14]
When I try to craft a stone button it appears quickly in the craft output and then it disappears. Even when I can pick the button it disappears in my inventory. So I can't craft stone buttons.

**Comment by AmauryCarrade** [comment]
Which version are you using?

**Comment by MGSchultz-13** [comment]
Version 1.1

**Comment by AmauryCarrade** [comment]
This bug was fixed but for some reason I forgot to update the resource on BukkitDev.
[This version should work just fine](http://jenkins.carrade.eu/job/BelovedBlocks/121/).

**Comment by MGSchultz-13** [comment]
Yes, it works. Thanks man.
