### ISSUE TITLE
Quartz block wrong return type on break

### ISSUE THREAD

**Issue by Romaq** [zDevelopers/BelovedBlocks#17]
This server is running CraftBukkit version git-Spigot-078e2f8-7f9fbe5 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Using CoreProtect and GriefPrevention

Place two quartz half-slabs. Break the double-slab quartz block. Get the "BB" smooth quartz block in return.

Turn a double-slab quartz block into a "BB" smooth quartz block using the stone cutter tool. Break the "BB" smooth quartz block, get two quartz returned.

This does not appear to be a problem with ordinary sand-stone.

**Comment by AmauryCarrade** [comment]
I will investigate on this when possible. Thanks for reporting.

**Comment by Romaq** [comment]
Thank you, bless you! I'll see if it behaves as expected with 1.11.
