### ISSUE TITLE
Expanded Permissions

### ISSUE THREAD

**Issue by Romaq** [zDevelopers/BelovedBlocks#18]
At the moment, it appears all permissions are related to "give" of either tools or blocks.

Permissions should include ability to create tools or "BB" blocks or to place them.

Currently, it appears we can not _place_ "BB" blocks. No permissions warning.

This server is running CraftBukkit version git-Spigot-078e2f8-7f9fbe5 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

We are also using CoreProtect and Grief Prevention.

**Comment by AmauryCarrade** [comment]
There are permissions for usage but the defaults are bad, we should fix that. I cannot fix that right now; you can either wait or give the permissions `belovedblocks.blocks.{block-name}.use` (e.g. `belovedblocks.blocks.end-portal.use`).

**Comment by prokopyl** [comment]
Permissions management has been improved in the latest commits.
From now on, players who try to use blocks or items without proper permission will be given a clear warning in their action bar.

A new `use` permission also has been implemented for each item, allowing players to place or use them or not (this is by default allowed for all players). A new `craft` permission is also being worked on, which should come relatively soon.

The permissions themselves also have been revamped, as they were clearly not working before, nor were very logical.

The model is now the following : `belovedblocks.<give/use/craft>.<blocks/tools>.<item>[.<self/other>]`.
Parent star-permission also have been correctly implemented, for example : 

* `belovedblocks.use.*` will allow all players to use all items (this is the default).
* `belovedblocks.give.blocks.birch.self` will allow players to give themselves birch log only (the `/bb give` command will only show allowed `give`s during autocompletion)
* `belovedblocks.give.tools.*` will allow players to give all tools (the saw and the stonecutter) to all players.

**Comment by Romaq** [comment]
Thank you!
